### ISSUE TITLE
Cannot connect to SignalK

### ISSUE THREAD

**Issue by MrTom1** [LukeSavage1306/Windlass-Remote-Chain-Counter-and-SignalK-Feed#3]
I followed exactly your settings to connect to SignalK, however I can not establish any connection. Port settings are same on both sides.
Any advice how to move ahead?

**Comment by LukeSavage1306** [comment]
Hi Tom, sorry for slow response.  Have you tried configuring the counter for stand alone use, and then tried connecting directly to its WiFi from your phone?  That way you can make sure that the chip is good and the code is running properly to begin with.   You would then know it is the signalk connection that is playing up rather than a duff chip or bad copy of the code.    Let me know how you get on and we can then work out the next step.

**Comment by MrTom1** [comment]
Hi Luke,
Thanks for your reply.
The board is working fine, I can connect to my smartphone and control it from there.
In SignalK I have added the corresponding UDP connection, but no data transfer to there.

**Comment by LukeSavage1306** [comment]
So what are the settings you have in the chain counter for connecting to your signal K server?  Do you want to copy and paste those few lines of code?   By the way - I have never done this sort of thing before or since taking Homberger’s counter and making the changes.  I learnt as I went along - largely by trial and error - and that was 2 1/2 years ago.  I only mention that as any help I can give now will also be largely by trial and error!!

**Comment by MrTom1** [comment]
So let's try it!
IP address for UDP to SignalK has been adapted (port is 4210, also setup in SignalK according to your manual):
IPAddress ip1(10, 81, 254, 242);           // IP Address to be used for SiganlK so that udp knows where to send messages - amend if yours is different
MMSI adapted:
  char udpmessage[1024];    //Next few lines send metadata to SignalK for chainlength - replace mmsi with your own "self" vessel details
      sprintf(udpmessage, "{\"context\": \"vessels.urn: mrn: imo: mmsi:211695590\",\"updates\": [{\"meta\":[{\"path\": \"navigation.anchor.chainlength\",\"value\": {\"units\": \"m\",\"description\": \"deployed chain length\",\"displayName\": \"Chain Length\",\"shortName\": \"DCL\"}}]}]}");

**Comment by LukeSavage1306** [comment]
And line 34 (which you would set to 0 to connect direct) has been reset to 1?

What are you running signalK on?  I used a Raspberry Pi where the default IP for a local host was 10.10.10.1 and that worked fine. I wonder whether in configuring your signalk server as well as changing the IP something else has been changed.

**Comment by LukeSavage1306** [comment]
Just re-reading my notes, once connected via the main WiFi (rather than using it standalone) can you access the chain counter from you phone?  But just can’t see the data in signalK?   Or can you not access it from your phone when using it as a client to the main WiFi?

**Comment by MrTom1** [comment]
#define WiFiMode_AP_STA 1  
IPAddress ip1(10, 81, 254, 242);           // IP Address to be used for SiganlK so that udp knows where to send messages - amend if yours is different

ip1 is the address of the ESP8266 board. This address I also use to run it from my smartphone. Does this address has to be changed? 
I changed ip1 to 10.10.10.1 (running on Raspberry Pi) and get the following with the monitor:
WiFi connected
IP address: 
10.81.254.242
Now listening at IP 10.81.254.242, UDP port 4210
Metadata sent to SignalKHTTP Server started
{"updates":[{"$source":"Windlass.Control","values":[{"path":"navigation.anchor.chainlength","value":1.650000}]}]}

**Comment by MrTom1** [comment]
See above, but still no data for "navigation.anchor.chainlength"

**Comment by LukeSavage1306** [comment]
From memory (as I did all of this on another computer at a different location)

The ESP connects to the general boat WiFi router and is allocated an IP address by DHCP.   Your phone, connected to the boat’s WiFi router, then connects to the ESP at the IP allocated via the boat’s router.  It sounds from what you are saying as if that bit is working OK??
Once you are happy that the ESP is accessible via the boat’s WiFi, so we know that it is hooked in, the next thing is then how to get the UDP messages into SignalK.  For that the ESP has to send the messages to the SignalK server running as “local host”.  I think, but can’t remember for sure, that is at 10.10.10.1
I’m afraid I am not going to be back at the location I did this at for a few weeks - and even then I would have to “start again” as, off the top of my head, I can’t even remember how one programmes the ESP from Arduino!!!

**Comment by LukeSavage1306** [comment]
Just looking at the code - line 38 is definitely telling the ESP the IP address of SignalK.  So it should be whatever IP your SignalK server is running at, not the IP of the ESP.  Something also makes me think that it sends data when there is an update to the value, not on a regular basis, so if you are not winding up or down it won’t be sending anything.  Not sure my knowledge of the coding is good enough to confirm that from “reading” it rather than trying it!

To help get it working (which took me days of trial and error) I wired up a simple switch to simulate the windlass switch - and I think changed the timeout time so that I could do it slowly

**Comment by MrTom1** [comment]
Got it running!
ip1 set to the correct address of the Raspi SignalK Server (10.81.254. ...) and it works fine!

Thanks for your time and advices!
Tom

**Comment by LukeSavage1306** [comment]
From. Looking at the code it looks like 304-309 sends the updated value to SignalK, and that seems to be nested within an IF statement that looks for a change in value.  So no change in value would suggest no value sent.  I may be wrong on that.  I don’t know how to “read” the code (or even what language it is);   I created it by copying from something else I found along with help from “JeremyP” (who I have never actually spoken to or met - just conversed with in the same way that I am with you!)

**Comment by LukeSavage1306** [comment]
At line 166 it seems you should see a line on the monitor if the metadata has been correctly sent.  Are you seeing that?

**Comment by LukeSavage1306** [comment]
Brilliant.  One thing to check when you install it.  Depending on the rating of your windlass power relay the current draw to operate the relay could be quite high.  Part of the redesign of the circuit board from Homberger’s original design was to upgrade the size of, and shorten the PCB tracks between the onboard relay and the connector.  On mine it seems OK - but you may want to check that the board isn’t getting hot in that area.

Good luck - I hope it makes your anchoring easier.  Where are you based by the way??

Luke

On 23 Aug 2022, at 15:25, MrTom1 ***@***.***> wrote:

﻿
Got it running!
ip1 set to the correct address of the Raspi SignalK Server (10.81.254. ...) and it works fine!

Thanks for your time and advices!
Tom

**Comment by MrTom1** [comment]
Good advice to check the current and signal line.

I'm based at Lake of Constance, Germany
Another happy user of the anchoring tool there now ;-)

**Comment by LukeSavage1306** [comment]
Great.  If you have any ideas on improvements let me know.  In the meantime I’m going to close the thread.
Regards
Luke
